firmware: https://downloads.circuitpython.org/bin/raspberry_pi_pico/en_US/adafruit-circuitpython-raspberry_pi_pico-en_US-7.3.3.uf2
tps:
  boot.py: H:/privat/git-sourcen/PythonTPS_SPS/picoTPS_2/boot.py
  code.py: H:/privat/git-sourcen/PythonTPS_SPS/picoTPS_2/code.py