firmware: https://raw.githubusercontent.com/willie68/PythonTPS_SPS/master/picoTPS_2/circuitpython/adafruit-circuitpython-raspberry_pi_pico-en_US-7.3.3.uf2
wipeware: https://raw.githubusercontent.com/willie68/PythonTPS_SPS/master/picoTPS_2/circuitpython/flash_nuke.uf2
tps:
  boot.py: https://raw.githubusercontent.com/willie68/PythonTPS_SPS/master/picoTPS_2/boot.py
  code.py: https://raw.githubusercontent.com/willie68/PythonTPS_SPS/master/picoTPS_2/code.py
